# Generated by Django 5.1 on 2024-09-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_examstudents_status_exam_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudents',
            name='exam_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
