# Generated by Django 5.1 on 2024-09-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0010_alter_questionpaper_option_four_and_more'),
        ('student_management', '0006_examstudents_status_exam_student'),
        ('valuation_management', '0002_markspfstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarksPfStudents',
            new_name='MarksOfStudents',
        ),
    ]
