# Generated by Django 5.1 on 2024-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_management', '0005_studentsresponse_student_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsresponse',
            name='student_input',
            field=models.IntegerField(),
        ),
    ]
