# Generated by Django 5.1 on 2024-10-08 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_management', '0015_remove_exam_question_paper_set_exam_questionnaire'),
        ('student_management', '0010_remove_student_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=10)),
                ('batch_name', models.CharField(max_length=100)),
                ('count_of_students', models.IntegerField()),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBatchMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_status', models.IntegerField(choices=[(0, 'exam scheduled for the student'), (1, 'exam started for the student'), (2, 'exam completed for the student'), (3, 'exam terminated for the student'), (4, 'student is rejected from the exam')], default=0)),
                ('exam_start_time', models.DateTimeField(null=True)),
                ('exam_end_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_batch_management.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
        ),
    ]
