# Generated by Django 5.1 on 2024-10-08 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0001_initial'),
        ('exam_management', '0015_remove_exam_question_paper_set_exam_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchmapping',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam'),
            preserve_default=False,
        ),
    ]
