# Generated by Django 5.1 on 2024-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0002_studentbatchmapping_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbatchmapping',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentbatchmapping',
            name='student_status',
            field=models.IntegerField(choices=[(0, 'exam scheduled for the student'), (1, 'exam started for the student'), (2, 'exam completed for the student'), (3, 'exam terminated for the student'), (4, 'student is rejected from the exam'), (5, 'student is shortlisted from the exam')], default=0),
        ),
    ]
