# Generated by Django 5.1 on 2024-11-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0004_alter_batch_table_alter_studentbatchmapping_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(choices=[(1, 'exam batch is open'), (2, 'exam batch is closed')], default=1),
        ),
    ]
