# Generated by Django 5.1 on 2024-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0005_alter_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_status',
            field=models.IntegerField(choices=[(1, 'exam batch is open'), (2, 'exam batch is closed')], default=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
