# Generated by Django 5.1 on 2024-08-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0001_initial'),
        ('institution_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='institution_management.institution'),
            preserve_default=False,
        ),
    ]
