# Generated by Django 5.1 on 2024-08-27 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0003_alter_exam_status'),
        ('question_category_management', '0001_initial'),
        ('question_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_question', models.IntegerField()),
                ('weightage', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
                ('question_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_category_management.questioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata')),
            ],
        ),
    ]
