# Generated by Django 5.1 on 2024-08-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0004_examquestioncategory_questionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.TimeField(),
        ),
    ]
