# Generated by Django 5.1 on 2024-08-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0007_exam_status_of_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_paper_set',
            field=models.BooleanField(default=False),
        ),
    ]
