# Generated by Django 5.1 on 2024-09-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0009_questionpaper_option_four_questionpaper_option_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='option_four',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='option_one',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='option_three',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='option_two',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
