# Generated by Django 5.1 on 2024-09-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0011_exam_cut_of_mark_alter_examquestioncategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='cut_of_mark',
            field=models.FloatField(null=True),
        ),
    ]
