# Generated by Django 5.1 on 2024-10-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0012_alter_exam_cut_of_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
