# Generated by Django 5.1 on 2024-10-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0013_examlocations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student_status',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam_management.examlocations'),
            preserve_default=False,
        ),
    ]
