# Generated by Django 5.1 on 2024-10-04 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0014_remove_exam_institution_remove_exam_student_status_and_more'),
        ('questionnaire_management', '0002_alter_questionnairecategories_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='question_paper_set',
        ),
        migrations.AddField(
            model_name='exam',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire_management.questionnaire'),
        ),
    ]
