# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0017_remove_examquestioncategory_weightage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='question_id',
        ),
        migrations.DeleteModel(
            name='ExamQuestionCategory',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
    ]
