# Generated by Django 5.1 on 2024-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0019_alter_exam_table_alter_examcriteria_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_pool',
            field=models.BooleanField(default=False),
        ),
    ]
