# Generated by Django 5.1 on 2024-08-22 12:52

import question_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='question_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=question_management.models.upload_path),
        ),
    ]
