# Generated by Django 5.1 on 2024-08-26 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0002_alter_questiondata_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'multiple choice question'), (1, 'trueorfalse'), (2, 'multiple choice selection')], default=0),
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata')),
            ],
        ),
    ]
