# Generated by Django 5.1 on 2024-08-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0003_questiondata_question_type_correctanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='correct_answer',
        ),
    ]
