# Generated by Django 5.1 on 2024-09-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0004_remove_questiondata_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='question_difficulty_level',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1),
        ),
    ]
