# Generated by Django 5.1 on 2024-10-01 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_category_management', '0001_initial'),
        ('question_management', '0007_remove_correctanswer_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='correct_answer_id',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='questiondata',
            name='option_id',
        ),
        migrations.AddField(
            model_name='correctanswer',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata'),
        ),
        migrations.AddField(
            model_name='options',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata'),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='question_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata'),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='question_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_category_management.questioncategory'),
        ),
    ]
