# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0010_delete_correctanswer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='options',
            table='options',
        ),
        migrations.AlterModelTable(
            name='questiondata',
            table='question',
        ),
        migrations.AlterModelTable(
            name='questionimage',
            table='question_image',
        ),
    ]
