# Generated by Django 5.1 on 2024-08-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0002_exam_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
