# Generated by Django 5.1 on 2024-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0005_alter_exam_exam_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_duration',
            field=models.IntegerField(default=60),
        ),
    ]
