# Generated by Django 5.1 on 2024-08-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0006_exam_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='status_of_exam',
            field=models.IntegerField(choices=[(0, 'exam scheduled'), (1, 'exam started'), (2, 'exam completed'), (3, 'exam cancelled')], default=0),
        ),
    ]
