# Generated by Django 5.1 on 2024-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0008_exam_question_paper_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='option_four',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='option_two',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
