# Generated by Django 5.1 on 2024-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0010_alter_questionpaper_option_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='cut_of_mark',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='examquestioncategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
