# Generated by Django 5.1 on 2024-10-07 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0015_remove_exam_question_paper_set_exam_questionnaire'),
        ('question_category_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_difficulty_level', models.IntegerField()),
                ('cut_off', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_category_management.questioncategory')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
            ],
        ),
    ]
