# Generated by Django 5.1 on 2024-10-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0016_examcriteria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examquestioncategory',
            name='weightage',
        ),
        migrations.AlterModelTable(
            name='examquestioncategory',
            table='exam_question_category',
        ),
    ]
