# Generated by Django 5.1 on 2024-10-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0018_remove_questionpaper_exam_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='exam',
        ),
        migrations.AlterModelTable(
            name='examcriteria',
            table='exam_criteria',
        ),
        migrations.AlterModelTable(
            name='examlocations',
            table='exam_location',
        ),
    ]
