# Generated by Django 5.1 on 2024-08-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0002_institution_institution_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_email',
            field=models.EmailField(max_length=100),
        ),
    ]
