# Generated by Django 5.1 on 2024-09-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0003_alter_institution_institution_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='coordinator_email',
            field=models.EmailField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='coordinator_name',
            field=models.CharField(default=123454321, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='coordinator_phone',
            field=models.CharField(default=1234567890, max_length=100),
            preserve_default=False,
        ),
    ]
