# Generated by Django 5.1 on 2024-10-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0004_institution_coordinator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
