# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0005_alter_institution_coordinator_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institution',
            table='institution',
        ),
    ]
