# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_category_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questioncategory',
            table='question_category',
        ),
    ]
