# Generated by Django 5.1 on 2024-09-30 06:58

import django.db.models.deletion
import question_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0005_questiondata_question_difficulty_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondata',
            name='question_image',
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(blank=True, max_length=255, null=True, upload_to=question_management.models.upload_path)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata')),
            ],
        ),
    ]
