# Generated by Django 5.1 on 2024-10-01 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0006_remove_questiondata_question_image_questionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswer',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='options',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='questionimage',
            name='question_id',
        ),
        migrations.AddField(
            model_name='questiondata',
            name='correct_answer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_management.correctanswer'),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='image_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_management.questionimage'),
        ),
        migrations.AddField(
            model_name='questiondata',
            name='option_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_management.options'),
        ),
    ]
