# Generated by Django 5.1 on 2024-10-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0008_remove_questiondata_correct_answer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
