# Generated by Django 5.1 on 2024-10-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0009_options_is_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
    ]
