# Generated by Django 5.1 on 2024-11-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0011_alter_options_table_alter_questiondata_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='option',
            field=models.CharField(max_length=1000),
        ),
    ]
