# Generated by Django 5.1 on 2024-08-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='exam_id',
            new_name='exam',
        ),
    ]
