# Generated by Django 5.1 on 2024-08-26 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0002_exam_institution'),
        ('institution_management', '0001_initial'),
        ('student_management', '0002_rename_exam_id_student_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution_management.institution'),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_management.exam'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
