# Generated by Django 5.1 on 2024-08-27 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0004_examquestioncategory_questionpaper'),
        ('student_management', '0003_student_institution_alter_student_exam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=1)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
        ),
    ]
