# Generated by Django 5.1 on 2024-08-28 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0004_examstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudents',
            name='link_sent',
            field=models.BooleanField(default=False),
        ),
    ]
