# Generated by Django 5.1 on 2024-08-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0005_examstudents_link_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudents',
            name='status_exam_student',
            field=models.IntegerField(choices=[(0, 'Registered for the exam'), (1, 'Exam started'), (2, 'Exam completed'), (3, 'Exam not completed')], default=0),
        ),
    ]
