# Generated by Django 5.1 on 2024-09-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_examstudents_exam_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='examstudents',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
