# Generated by Django 5.1 on 2024-09-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_examstudents_is_shortlisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='no_of_backlogs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
