# Generated by Django 5.1 on 2024-09-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0009_student_cgpa_student_no_of_backlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='exam',
        ),
    ]
