# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0010_remove_student_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='token',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.DeleteModel(
            name='ExamStudents',
        ),
    ]
