# Generated by Django 5.1 on 2024-10-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0012_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.IntegerField(choices=[(1, 'Bachelor of Technology in Computer Science and Engineering'), (2, 'Bachelor of Technology in Information Technology'), (3, 'Bachelor of Engineering in Computer Science and Engineering'), (4, 'Bachelor of Engineering in Information Technology'), (5, 'Bachelor of Computer Applications'), (6, 'Master of Computer Applications'), (7, 'Master of Computer Science'), (8, 'Bachelor of Science in Computer Science'), (9, 'Bachelor of Engineering in Artificial Intelligence and Data Science')]),
        ),
    ]
