# Generated by Django 5.1 on 2024-09-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_management', '0010_alter_questionpaper_option_four_and_more'),
        ('question_management', '0004_remove_questiondata_correct_answer'),
        ('student_management', '0006_examstudents_status_exam_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_management.questiondata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
        ),
    ]
