# Generated by Django 5.1 on 2024-09-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_management', '0010_alter_questionpaper_option_four_and_more'),
        ('student_management', '0006_examstudents_status_exam_student'),
        ('valuation_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksPfStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_management.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management.student')),
            ],
        ),
    ]
