# Generated by Django 5.1 on 2024-10-08 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0002_studentbatchmapping_exam'),
        ('question_category_management', '0001_initial'),
        ('valuation_management', '0003_rename_markspfstudents_marksofstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsresponse',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentsresponse',
            name='student',
        ),
        migrations.CreateModel(
            name='QuestionCategoryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_difficulty_level', models.IntegerField()),
                ('correct_answer_count', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_category_management.questioncategory')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_batch_management.studentbatchmapping')),
            ],
        ),
        migrations.DeleteModel(
            name='MarksOfStudents',
        ),
    ]
