# Generated by Django 5.1 on 2024-10-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0002_studentbatchmapping_exam'),
        ('valuation_management', '0004_remove_studentsresponse_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsresponse',
            name='student_input',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentsresponse',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_batch_management.studentbatchmapping'),
        ),
    ]
