# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valuation_management', '0006_alter_studentsresponse_student_input'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questioncategoryresponse',
            table='student_responses_category_wise',
        ),
        migrations.AlterModelTable(
            name='studentsresponse',
            table='students_responses',
        ),
    ]
