# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_batch_management', '0003_studentbatchmapping_correct_count_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
        migrations.AlterModelTable(
            name='studentbatchmapping',
            table='student_batch_mapping',
        ),
    ]
