

services:
  client:
    build: ./client # This should point to the directory containing the Dockerfile
    container_name: client_c
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: recruit_demo_4
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s


  web:
    build:
      context: ./server  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app

    depends_on:
          db:
            condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  # test:
  #   build: ./client
  #   container_name: test
  #   command: npm test
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=test


volumes:
  db_data: