# Generated by Django 5.1 on 2024-09-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0002_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
