# Generated by Django 5.1 on 2024-09-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0003_feedbacks_created_at_feedbacks_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
