# Generated by Django 5.1 on 2024-09-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0005_alter_feedbacks_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
