# Generated by Django 5.1 on 2024-10-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0007_adminemails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='adminemails',
            table='admin_email',
        ),
        migrations.AlterModelTable(
            name='feedbacks',
            table='feedback',
        ),
    ]
