# Generated by Django 5.1 on 2024-08-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_email',
            field=models.EmailField(max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_phone',
            field=models.CharField(default=1234567890, max_length=15),
            preserve_default=False,
        ),
    ]
