# Generated by Django 5.1 on 2024-10-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0006_alter_institution_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
