# Generated by Django 5.1 on 2024-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_management', '0007_alter_institution_coordinator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
