# Generated by Django 5.1 on 2024-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecategories',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
