# Generated by Django 5.1 on 2024-10-06 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_category_management', '0001_initial'),
        ('question_management', '0008_remove_questiondata_correct_answer_id_and_more'),
        ('questionnaire_management', '0002_alter_questionnairecategories_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairecategories',
            name='question_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_categories', to='question_category_management.questioncategory'),
        ),
        migrations.AlterField(
            model_name='questionnairecategories',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='questionnaire_management.questionnaire'),
        ),
        migrations.AlterField(
            model_name='questionnairequestions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='question_management.questiondata'),
        ),
        migrations.AlterField(
            model_name='questionnairequestions',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire_management.questionnaire'),
        ),
        migrations.CreateModel(
            name='QuestionnaireQuestionsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_options', to='questionnaire_management.questionnaire')),
                ('questionnaire_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_question_options', to='question_management.options')),
                ('questionnaire_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_questions', to='questionnaire_management.questionnairequestions')),
            ],
        ),
    ]
