# Generated by Django 5.1 on 2024-10-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_management', '0003_alter_questionnairecategories_question_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionnaireQuestionsOptions',
        ),
    ]
