# Generated by Django 5.1 on 2024-10-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_management', '0004_delete_questionnairequestionsoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairecategories',
            name='score',
        ),
        migrations.AlterModelTable(
            name='questionnaire',
            table='questionnaire',
        ),
        migrations.AlterModelTable(
            name='questionnairecategories',
            table='questionnaire_categories',
        ),
        migrations.AlterModelTable(
            name='questionnairequestions',
            table='questionnaire_questions',
        ),
    ]
