# Generated by Django 5.1 on 2024-10-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire_management', '0005_remove_questionnairecategories_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionnaireCategories',
        ),
    ]
